# Generated by Django 6.0.3 on 2026-03-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rede_social", models.CharField(max_length=100)),
                ("legenda", models.TextField(blank=True, null=True)),
                (
                    "midia",
                    models.ImageField(blank=True, null=True, upload_to="divulgacao/"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
