# Generated by Django 6.0.3 on 2026-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_hubpub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="hora",
            field=models.CharField(default="00:00", max_length=100),
        ),
        migrations.AddField(
            model_name="projeto",
            name="tipo_post",
            field=models.CharField(default="Post Simples", max_length=100),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="legenda",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="rede_social",
            field=models.CharField(default="Não Especificada", max_length=100),
        ),
    ]
