# Generated by Django 6.0.3 on 2026-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_hubpub",
            "0002_projeto_hora_projeto_tipo_post_alter_projeto_legenda_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projeto",
            new_name="divulgacao_agend",
        ),
    ]
