# Generated by Django 6.0.3 on 2026-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_hubpub", "0003_rename_projeto_divulgacao_agend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divulgacao_agend",
            name="data_criacao",
            field=models.DateTimeField(),
        ),
    ]
