# Generated by Django 6.0.3 on 2026-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_hubpub", "0004_alter_divulgacao_agend_data_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divulgacao_agend",
            name="data_criacao",
            field=models.DateField(),
        ),
    ]
