# Generated by Django 6.0.3 on 2026-03-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_hubpub", "0005_alter_divulgacao_agend_data_criacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="divulgacao_agend",
            name="ultima_publicacao",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
